### ISSUE TITLE
modprobe: FATAL: Module libiscsi not found in directory /lib/modules/5.10.102.1-microsoft-standard-WSL2+

### ISSUE THREAD

**Issue by gameboycool** [jovton/USB-Storage-on-WSL2#14]
I could done every step in 3. Linux Kernel Modules as URL below, only failed at modprobe -v libiscsi and the rest
https://github.com/jovton/USB-Storage-on-WSL2

my config-wsl
https://github.com/gameboycool/WSL2/blob/main/config-wsl

**Comment by gameboycool** [comment]
my WSL is debian
and I also tried ubuntu, modprobe works
so closed for now

**Comment by minyilee95** [comment]
Just to make sure, the mod probe worked fine when you followed the same instructions on Ubuntu?
