### ISSUE TITLE
bc missing from install

### ISSUE THREAD

**Issue by quonic** [jovton/USB-Storage-on-WSL2#3]
When running through the commands from a fresh install bc was missing.

I think adding bc to the apt install command would help others a little bit.

~~`sudo apt install build-essential flex bison libssl-dev libelf-dev libncurses5-dev git`~~

`sudo apt install build-essential flex bison libssl-dev libelf-dev libncurses5-dev git bc`

**Comment by jovton** [comment]
Thank you for the suggestion. I've added it to the instructions.
