### ISSUE TITLE
can't compile kernel

### ISSUE THREAD

**Issue by mahyar1284** [jovton/USB-Storage-on-WSL2#4]
this is the error after making changes in menuconfig:

mahyar1284@Mahyar1284:~/my_projects/WSL2-Linux-Kernel$ sudo make && make modules_install
[sudo] password for mahyar1284:
  CALL    scripts/checksyscalls.sh
  DESCEND  objtool
  CHK     include/generated/compile.h
Kernel: arch/x86/boot/bzImage is ready  (#1)
  Building modules, stage 2.
  MODPOST 4 modules
mkdir: cannot create directory ‘/lib/modules/4.19.84-microsoft-standard+’: Permission denied
make: *** [Makefile:1258: _modinst_] Error 1

**Comment by wanfuse123** [comment]
try this sudo make KCONFIG_CONFIG=Microsoft/config-wsl before sudo make modules_install

**Comment by jovton** [comment]
Thanks for the feedback. :) I will make the necessary changes to the article as suggested by @wanfuse123.

**Comment by mahyar1284** [comment]
Thanks guys. The problem solved. So, I close this issue.
